rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'


urlpatterns = [
path('', views.cover, name='cover'),
path('bookshelf/', views.bookshelf, name='bookshelf'),
path('bookshelf_user/', views.bookshelf_user, name='bookshelf_user'),
path('index/<slug:source_title_slug>/', views.index, name='index'),
path('about/', views.about, name='about'),
path('contact_us/', views.contact_us, name='contact_us'),
path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
path('add_category/', views.add_category, name='add_category'),
path('category/<slug:category_name_slug>/add_vocabulary/', views.add_vocabulary, name='add_vocabulary'),
path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
# path('register/', views.register, name='register'),
# path('login/', views.user_login, name='login'),
path('restricted/', views.restricted, name='restricted'),
path('sentence/', views.show_sentence, name='show_sentence'),
# path('kanshu/', views.kanshu, name='kanshu'),
path('like_category/', views.like_category, name='like_category'),
path('bookmark/', views.bookmark, name='bookmark'),
path('add_word2dict/', views.add_word2dict, name='add_word2dict'),
path('del_word2dict/', views.del_word2dict, name='del_word2dict'),
path('words_in_sent/', views.words_in_sent, name='words_in_sent'),
path('learnt/', views.learnt, name='learnt'),
path('edit/<slug:source_title_slug>/', views.edit, name='edit'),
path('useredit/', views.useredit, name='useredit'),
# path('next_kanshu/', views.next_kanshu, name='next_kanshu'),
path('kanshu_sentence/<slug:source_title_slug>/', views.kanshu_sentence, name='kanshu_sentence'),
path('kanshu_sentence2/<slug:source_title_slug>/', views.mother_text_helper_sentence, name='mother_text_helper_sentence'),
path('kanshu_carousel/<slug:source_title_slug>/', views.kanshu_carousel, name='kanshu_carousel'),
path('kanshu_carousel2/<slug:source_title_slug>/', views.mother_text_helper, name='mother_text_helper'),
# path('personal_kanshu/', views.personal_kanshu, name='personal_kanshu'),
path('personal_kanshu/<slug:source_title_slug>/', views.personal_kanshu_source, name='personal_kanshu_source'),

path('personal_kanshu_source_delete/<slug:source_title_slug>/', views.personal_kanshu_source_delete, name='personal_kanshu_source_delete'),
path('personal_kanshu_index_delete/', views.personal_kanshu_index_delete, name='personal_kanshu_index_delete'),

path('personal_kanshu_index/', views.personal_kanshu_index, name='personal_kanshu_index'),
path('kanshu_dashboard/', views.kanshu_dashboard, name='kanshu_dashboard'),
path('register_profile/', views.register_profile, name='register_profile'),
path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
path('text2speechtest/', views.text2speechtest, name='text2speechtest'),
# path('logout/', views.user_logout, name='logout'),
path('password_reset/', views.password_reset_request, name="password_reset"),
]

tango_with_django_project/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

from django.conf import settings
from django.conf.urls import include, url  # For django versions before 2.0
from django.urls import include, path  # For django versions from 2.0 and up


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


urlpatterns = [
    path('', views.cover, name='cover'),
    # path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
                       name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                      template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                      template_name='password/password_reset_complete.html'), name='password_reset_complete'),


                  path('accounts/register/',
        MyRegistrationView.as_view(),
        name ='registration_register'),

    path('accounts/', include('registration.backends.simple.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango. path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

rango/views.py
from django.template import RequestContext
from django.shortcuts import render, redirect
from rango.forms import CategoryForm, VocabForm, SentenceForm, ContactForm, EditForm, UserEditForm, UserVocabForm
from rango.forms import UserForm, UserProfileForm, UserUploadForm
from rango.edit import editword, usereditword
from django.template.loader import render_to_string
from django.http import HttpResponse
from rango.models import Chapter, About, HSK, Category, Vocab, Sentence, Source, MotherText, UserSource, UserPrevious, UserVocab, UserCategory, UserSentence, UserBookmark, UserDictionary
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
from googletrans import Translator
from rango.kanshu import run_kanshu
from rango.user_kanshu import doc_process, binfile_to_db, run_user_kanshu
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from rango.models import UserProfile
from django.views import View
from django.utils.decorators import method_decorator

from django.contrib import messages
from django.contrib.auth.forms import PasswordResetForm
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.core.mail import send_mail, BadHeaderError
from django.db.models.query_utils import Q


import json
from django.http import JsonResponse
import string
from django.core.files.storage import FileSystemStorage

def text2speechtest(request):

    context_dict = {}

    return render(request, 'rango/text2speechtest.html', context=context_dict)

def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "password/password_reset_email.txt"
                    c = {
                    "email":user.email,
                    'domain':'http://bookshelf.kanshuchinese.com',
                    'site_name': 'Kanshu',
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "user": user,
                    'token': default_token_generator.make_token(user),
                    'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'kanshuapp@gmail.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/password_reset.html", context={"password_reset_form":password_reset_form})




def useredit(request):
    user= request.user
    delete_session(request, 'result_list')
    delete_session(request, 'sides')
    form = UserVocabForm()
    if request.method == 'POST':
        form = UserVocabForm(request.POST, current_user=request.user)
        if form.is_valid():
            newword = form.save(commit=False)
            print('user.id: ' + str(user.id))
            print('newword.source.id: ' + str(newword.source.id))
            print('newword.chinese: ' + str(newword.chinese))

            try:

                v = UserVocab.objects.get(user_id=user.id, source_id=newword.source.id, chinese=newword.chinese)
                print(str(v))
                frequency = v.frequency
                v.delete()

                print('deleted v')
            except:
                print('editing word not found')
                frequency = 1
            newword.user = user
            pinyin = usereditword(user, newword.source, newword.chinese, newword.category)

            newword.pinyin = pinyin
            newword.frequency = frequency


            newword.save()
            return redirect(reverse('rango:personal_kanshu_index'))
        else:

            print(form.errors)

    return render(request, 'rango/useredit.html', {'form': form})


def edit(request, source_title_slug):
    print('source_title_slug:', source_title_slug)
    s = source_helper(source_title_slug.lower())
    source = s['source_id']
    print('source: ', str(source))
    context_dict = {}
    context_dict['source'] = str(source).lower()
    delete_session(request, 'result_list')
    delete_session(request, 'sides')
    form = EditForm()

    if request.method == 'POST':

        form = EditForm(request.POST)
        if form.is_valid():
            word = form.cleaned_data['word']
            print('word: '+ word)
            tag = form.cleaned_data['tag']
            print('tag: ' + tag)
            english = form.cleaned_data['english']
            print('english: ' + english)
            source = s['source_id']
            print('source from post is: ' + str(source))
            words = {'word':word, 'tag':tag, 'english': english}
            editword(s, words)
            return redirect(reverse('rango:kanshu_sentence', kwargs={'source_title_slug': source_title_slug}))

        else:
            print(form.errors)
    context_dict['form'] = form
    return render(request, 'rango/edit.html', context=context_dict)


def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # send email code goes here
            sender_name = form.cleaned_data['name']
            sender_email = form.cleaned_data['email']

            message = "{0} of {1} has sent you a new message:\n\n{2}".format(sender_name, sender_email, form.cleaned_data['message'])
            send_mail('New Enquiry', message, 'kanshuapp@gmail.com', ['kanshuchinese@gmail.com'], fail_silently=False)
            messages.success(request, "Message sent!")
            return HttpResponse('<h1>Thanks for contacting me! Click back button</h1>')
    else:
        form = ContactForm()

    return render(request, 'rango/contact_us.html', {'form': form})


def cover(request):
    context_dict = {}


    # Render the response and send it back!
    return render(request, 'rango/cover.html', context=context_dict)

# hgjiyhkhjkhjklh
def addremovebook(request, source_title_slug):

    s = Source.objects.filter(slug=source_title_slug)

    for i in r:

        s = Source.objects.get(title=i['title'])
        word_count=len(list(Vocab.objects.filter(source=s).values('chinese')))

        print(i['title'])
        title.append(i['title'])
        text.append(i['type'])
        author.append(i['author'])
        content.append((i['title'], i['type'], i['author'], i['slug'], i['picture'], str(word_count)))

    context_dict = {}
    s = source_helper(request.user)
    context_dict['title'] = s['title']
    # Render the response and send it back!

    def add_vocab(category, chinese, english, pinyin, learnt=0, score=0, previous=0, frequency=0):
        p = Vocab.objects.get_or_create(category=category, chinese=chinese, english=english, pinyin=pinyin)[0]
        p.score = score
        p.frequency = frequency
        p.previous = previous
        p.learnt = learnt
        p.save()
        return p

    return render(request, 'rango/cover.html', context=context_dict)



def bookshelf(request):
    context_dict = {}
    r = list(Source.objects.filter(language="Mandarin").values('title', 'type', 'author', 'picture', 'about_book', 'about_author'))

    title=[]
    text=[]
    author=[]
    content=[]
    about_book=[]
    about_author=[]

    for i in r:

        s = Source.objects.get(title=i['title'])
        word_count=len(list(Vocab.objects.filter(source=s).values('chinese')))

        print(i['title'])
        title.append(i['title'])
        text.append(i['type'])
        author.append(i['author'])
        about_author.append(i['about_author'])
        about_book.append(i['about_book'])
        content.append((i['title'], i['type'], i['author'], i['picture'], str(word_count)))

    context_dict['titles'] = title
    context_dict['texts'] = text
    context_dict['authors'] = author
    context_dict['contents'] = content



    print(about_author, about_book)
    # Render the response and send it back!
    return render(request, 'rango/bookshelf.html', context=context_dict)

@login_required
def bookshelf_user(request):
    context_dict = {}
    r = list(Source.objects.filter(language="Mandarin").values('title', 'slug', 'type', 'author', 'picture', 'about_book', 'about_author'))

    print(r)
    title=[]
    text=[]
    author=[]
    content=[]
    about_book=[]
    about_author=[]

    for i in r:

        s = Source.objects.get(title=i['title'])
        word_count=len(list(Vocab.objects.filter(source=s).values('chinese')))

        title.append(i['title'])
        text.append(i['type'])
        author.append(i['author'])
        about_author.append(i['about_author'])
        about_book.append(i['about_book'])
        content.append((i['about_author'], i['about_book'], i['title'], i['type'], i['author'], i['picture'], i['slug'], str(word_count)))

    context_dict['titles'] = title
    context_dict['texts'] = text
    context_dict['authors'] = author
    context_dict['contents'] = content

    for line in context_dict:
        print("\n")
        print(line, '\n')

    print('\n\ncontext_dict: ', context_dict)
    # Render the response and send it back!
    return render(request, 'rango/bookshelf_user.html', context=context_dict)


@login_required
def personal_kanshu_source(request, source_title_slug):

templates/rango/add_vocabulary.html
{% extends 'rango/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}
    Add a Word
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a word to {{ category.name }}</h1>
        <div class="p-2"></div>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="page_form" method="post" action="{% url 'rango:add_vocabulary' category.slug %}" enctype="multipart/form-data">
            {% csrf_token %}
            <p></p>
            {{ form|crispy }}
            <div class="p-2"></div>
            <input class="btn btn-lg btn-primary" type="submit" value="Update" />
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/add_vocabulary_old.html
{% extends 'rango/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}
    Add a Word
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a word to {{ category.name }}</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="page_form" method="post" action="{% url 'rango:add_vocabulary' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">Add to vocabulary</button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/base_kanshu_carousel_original.html
<!doctype html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">

<head>
<style>
    .remove_button_css {
  outline: none;
  padding: 5px;
  border: 0px;
  box-sizing: none;
  background-color: transparent;
  .remove_button_css:focus,
}
.remove_button_css:hover {
    color: #23527c;
    text-decoration: underline;
}
</style>
<style>
/* Modify the background color */
.navbar-custom {
background-color: #99213b;
}

.navbar-brand {
background-color: #99213b;
}
</style>
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 20px;
}

#myBtn {
  display: none;
  position: fixed;
  bottom: 20px;
  right: 30px;
  z-index: 99;
  font-size: 18px;
  border: none;
  outline: none;
  background-color: red;
  color: white;
  cursor: pointer;
  padding: 15px;
  border-radius: 4px;
}

#myBtn:hover {
  background-color: #555;
}

#bookmark_btn {
  display: none;
  position: fixed;
  bottom: 100px;
  right: 30px;
  z-index: 99;
  font-size: 18px;
  border: none;
  outline: none;
  background-color: blue;
  color: white;
  cursor: pointer;
  padding: 15px;
  border-radius: 4px;
}

#bookmark_btn:hover {
  background-color: #333;
}
</style>
<style>
    .modal-backdrop {
     background-color: rgba(0,0,0,.0001) !important;
}
</style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A slideshow component for cycling through elements—images or slides of text—like a carousel.">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <meta name="docsearch:language" content="en">
    <meta name="docsearch:version" content="4.3">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>Kanshu Carousel</title>

  <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Custom styles for this template -->


    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.21/af-2.3.5/b-1.6.2/b-colvis-1.6.2/b-flash-1.6.2/b-html5-1.6.2/b-print-1.6.2/cr-1.5.2/r-2.2.5/sc-2.0.2/sp-1.1.1/datatables.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">


    <style type="text/css" class="init"></style>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <script type="text/javascript" class="init">



    $(document).ready(function() {
        $('.dataTable').DataTable({
                    pageLength: 500,
                    lengthMenu: [ 100, 200, 500, 1000, 5000, 10000 ],
                    paging: true,
                    searching: true,
                    columnDefs: [
                        { responsivePriority: 1, targets: 0 },
                        { responsivePriority: 10001, targets: 4 },
                        { responsivePriority: 2, targets: -2 }
                    ],
                    dom: 'Blfrtip',
                    buttons: [ 'copy', 'excel', 'print' ]
        });
    } );
    </script>


    <style id="holderjs-style" type="text/css"></style>

</head>

<a name="top"></a>
<body>

<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
<button data-categoryid7="{{ sentence_number }}"
        data-categoryid8="{{ source.slug }}"
        class="btn btn-primary btn-sm"
        type="button"
        id="bookmark_btn" title="bookmark">Bookmark</button>
<script>
//Get the button
var mybutton = document.getElementById("myBtn");
var bkmbutton = document.getElementById("bookmark_btn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
    bkmbutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
    bkmbutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>


<header>
  <div class="collapse navbar-custom" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-white">{{ get_about }}</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="https://www.linkedin.com/in/priyesh-patel-77b77529" class="text-white">Follow on Linkedin</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="{% url 'rango:contact_us' %}" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

      <div class="navbar navbar-dark navbar-custom box-shadow">
        <div class="container d-flex justify-content-between">
      <a href="{% url 'rango:cover' %}" class="navbar-brand d-flex align-items-center">
<!--        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" class="bi bi-bookshelf" viewBox="0 0 16 16">-->
<!--          <path d="M2.5 0a.5.5 0 0 1 .5.5V2h10V.5a.5.5 0 0 1 1 0v15a.5.5 0 0 1-1 0V15H3v.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 .5-.5zM3 14h10v-3H3v3zm0-4h10V7H3v3zm0-4h10V3H3v3z"/>-->
<!--        </svg>-->
<!--          <strong>Kanshu</strong>-->
        <img src="{% static 'images/kanshu.jpg' %}" alt="kanshu" width="140" />
      </a>
        <nav class="navbar navbar-fixed-top navbar-expand-md navbar-light bg-faded">
          <ul class="navbar-nav mr-auto ">
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'rango:bookshelf_user' %}">Bookshelf</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Your Profile</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'rango:kanshu_dashboard' %}">Dashboard</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
            <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
          </ul>
        </nav>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<div class="container-fluid">
    <div class="row">
<a name="top"></a>
<main role="main" class="col-md-12  ml-sm-auto col-lg-12 px-4">
{% block body_block %}{% endblock %}
                    <!-- FOOTER -->
        <footer class="text-muted py-5">
          <div class="container">
            <p class="float-end mb-1">
              <a href="#top">Back to top</a>
            </p>
            <p class="mb-1">Kanshu &copy; created by Priyesh Patel!</p>
            <p class="mb-0">New to Kanshu? <a href="https://www.kanshuchinese.com/">Visit the landing page</a>.</p>
          </div>
        </footer>
</main>
    </div>
</div>

<!-- Bootstrap core JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->

        <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="{% static "js/rango-jquery.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/rango-ajax.js" %}" crossorigin="anonymous"></script>
<!--        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery.min.js"><\/script>')</script>-->



</body>
</html>

templates/rango/base_old.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <div> <!-- Sidebar block added. DM -->
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                <li><a href="{% url 'auth_password_change' %}">Change your Password</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/kanshu_dashboard.html
{% extends 'rango/base_user_dashboard.html' %}
{% load static %}

templates/rango/personal_kanshu2.html
{% extends 'rango/personal_kanshu' %}
{% load static %}